server:
  port: 8090
  servlet:
    context-path: /sforum

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/forumdb?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Shanghai&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
      validation-query: select 1 from dual
  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: localhost
    port: 6379
    timeout: 300 # 连接超时时间（毫秒
    jedis:
      pool:
        max-active: 8
        max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接